#!/bin/bash

if [ $# -ne 0 ]; then
    echo "Usage: cat /path/to/trace | $0" >&2; exit 1
fi

pushd `dirname $0` > /dev/null

PROBEDIR=../probe
java -cp ${PROBEDIR}/probe.jar:${PROBEDIR}/gxl.jar:./build Trace2GXL
